import { useState, type ReactNode } from 'react'
import { LayoutGrid, Package, Tags, Droplets, MessageCircle, Users, Star, FileText, Languages, Menu, Home, Phone, Search, Image, Settings, ArrowUp, ArrowDown, Eye, EyeOff, Trash2, Plus, Check, X, ExternalLink } from 'lucide-react'
import { useCMS, brl, type Product, type OrderLead } from './cms'
import { useRouter } from './motion'
import { Logo, Stars, IgTile, Instagram } from './ui'

const SECTIONS_ADMIN = [
  ['overview', 'Overview', LayoutGrid], ['products', 'Products', Package], ['categories', 'Categories', Tags], ['fragrances', 'Fragrances', Droplets],
  ['leads', 'Orders / WhatsApp Leads', MessageCircle], ['customers', 'Customers', Users], ['reviews', 'Reviews', Star], ['instagram', 'Instagram Content', Instagram],
  ['pages', 'Pages', FileText], ['translations', 'Translations', Languages], ['navigation', 'Navigation', Menu], ['homepage', 'Homepage', Home],
  ['contact', 'Contact Information', Phone], ['seo', 'SEO', Search], ['media', 'Media Library', Image], ['settings', 'Settings', Settings],
] as const

const Card = ({ children, className = '' }: { children: ReactNode; className?: string }) => <div className={`border border-beige bg-cream ${className}`}>{children}</div>
const H = ({ title, sub, action }: { title: string; sub?: string; action?: ReactNode }) => <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-4xl font-light md:text-5xl">{title}</h1>{sub && <p className="mt-2 text-sm text-taupe">{sub}</p>}</div>{action}</div>
const Btn = ({ children, onClick, ghost }: { children: ReactNode; onClick?: () => void; ghost?: boolean }) => <button onClick={onClick} className={`eyebrow inline-flex items-center gap-2 px-4 py-2.5 !text-[10px] transition ${ghost ? 'border border-beige hover:border-soft' : 'bg-soft text-cream hover:bg-gold'}`}>{children}</button>
const In = ({ label, value, onChange, area, max, type = 'text' }: { label: string; value: string | number; onChange: (v: string) => void; area?: boolean; max?: number; type?: string }) => {
  const len = String(value).length; const over = max && len > max
  return (
    <label className="block">
      <span className="eyebrow flex justify-between !text-[9px] text-taupe"><span>{label}</span>{max && <span className={over ? 'text-red-800' : len > max * 0.85 ? 'text-gold' : ''}>{len}/{max}</span>}</span>
      {area ? <textarea rows={3} value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 w-full resize-none border border-beige bg-ivory px-3 py-2.5 text-sm outline-none focus:border-gold" /> : <input type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 w-full border border-beige bg-ivory px-3 py-2.5 text-sm outline-none focus:border-gold" />}
      {max && <span className="mt-1 block h-px bg-beige"><span className={`block h-px transition-all ${over ? 'bg-red-800' : 'bg-gold'}`} style={{ width: `${Math.min(100, (len / max) * 100)}%` }} /></span>}
    </label>
  )
}
const Toggle = ({ on, onClick, label }: { on: boolean; onClick: () => void; label?: string }) => <button role="switch" aria-checked={on} aria-label={label} onClick={onClick} className={`relative h-5 w-9 rounded-full transition-colors duration-500 ${on ? 'bg-gold' : 'bg-beige'}`}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-cream transition-transform duration-500 ease-out-lux ${on ? 'translate-x-4' : 'translate-x-0.5'}`} /></button>
const Th = ({ children }: { children: ReactNode }) => <th className="eyebrow border-b border-beige px-4 py-3 text-left !text-[9px] font-medium text-taupe">{children}</th>
const Td = ({ children, className = '' }: { children: ReactNode; className?: string }) => <td className={`border-b border-beige/70 px-4 py-3 align-middle text-sm ${className}`}>{children}</td>

function ProductEditor({ p, onSave, onClose }: { p: Product; onSave: (p: Product) => void; onClose: () => void }) {
  const [d, setD] = useState(p); const { fragrances, categories } = useCMS()
  const s = (k: keyof Product, v: unknown) => setD({ ...d, [k]: v })
  return (
    <div className="fixed inset-0 z-[66] flex justify-end">
      <div className="absolute inset-0 bg-soft/40" onClick={onClose} />
      <div className="relative h-full w-full max-w-2xl overflow-y-auto bg-ivory p-8">
        <div className="mb-8 flex items-center justify-between"><h2 className="font-serif text-3xl">{d.name.pt || 'Novo produto'}</h2><button onClick={onClose}><X strokeWidth={1} /></button></div>
        <div className="grid gap-5 sm:grid-cols-2">
          <In label="Product Name — PT" value={d.name.pt} onChange={(v) => s('name', { ...d.name, pt: v })} /><In label="Product Name — EN" value={d.name.en} onChange={(v) => s('name', { ...d.name, en: v })} />
          <In area label="Description — PT" value={d.desc.pt} onChange={(v) => s('desc', { ...d.desc, pt: v })} /><In area label="Description — EN" value={d.desc.en} onChange={(v) => s('desc', { ...d.desc, en: v })} />
          <In type="number" label="Price (R$)" value={d.price} onChange={(v) => s('price', +v)} /><In type="number" label="Promotional price" value={d.promo ?? ''} onChange={(v) => s('promo', v ? +v : undefined)} />
          <label className="block"><span className="eyebrow !text-[9px] text-taupe">Category</span><select value={d.cat} onChange={(e) => s('cat', e.target.value)} className="mt-2 w-full border border-beige bg-ivory px-3 py-2.5 text-sm">{categories.map((c) => <option key={c.id} value={c.id}>{c.name.pt}</option>)}</select></label>
          <label className="block"><span className="eyebrow !text-[9px] text-taupe">Fragrance</span><select value={d.frag} onChange={(e) => s('frag', e.target.value)} className="mt-2 w-full border border-beige bg-ivory px-3 py-2.5 text-sm">{fragrances.map((f) => <option key={f.id} value={f.id}>{f.name.pt}</option>)}</select></label>
          <In label="Weight / Volume" value={d.size} onChange={(v) => s('size', v)} /><In label="Slug" value={d.id} onChange={(v) => s('id', v)} />
          <In label="SEO title" max={60} value={d.name.pt + ' | São Paulo Aroma'} onChange={() => {}} /><In label="SEO description" max={160} value={d.desc.pt} onChange={() => {}} />
        </div>
        <p className="eyebrow mb-3 mt-8 !text-[9px] text-taupe">Images · first is thumbnail</p>
        <div className="grid gap-3">
          {d.imgs.map((img, k) => <div key={k} className="flex items-center gap-3"><img src={img} alt="" className={`h-20 w-16 object-cover ${k === 0 ? 'ring-1 ring-gold ring-offset-2' : ''}`} /><input aria-label={`Image ${k + 1} URL`} value={img} onChange={(e) => s('imgs', d.imgs.map((x, i) => i === k ? e.target.value : x))} className="min-w-0 flex-1 border border-beige bg-ivory px-3 py-2 text-xs outline-none focus:border-gold" /><button aria-label="Remover imagem" onClick={() => s('imgs', d.imgs.filter((_, i) => i !== k))}><Trash2 className="h-4 w-4 text-taupe" strokeWidth={1} /></button></div>)}
          <button onClick={() => s('imgs', [...d.imgs, ''])} className="eyebrow flex items-center gap-2 self-start border border-dashed border-taupe px-3 py-2 !text-[9px] text-taupe"><Plus className="h-3.5 w-3.5" strokeWidth={1} />Adicionar imagem por URL</button>
        </div>
        <div className="mt-8 flex flex-wrap gap-8 text-sm">{(['published', 'stock', 'featured'] as const).map((k) => <span key={k} className="flex items-center gap-3"><Toggle on={d[k]} onClick={() => s(k, !d[k])} />{k === 'published' ? 'Publicado' : k === 'stock' ? 'Em estoque' : 'Destaque'}</span>)}</div>
        <div className="mt-10 flex gap-3"><Btn onClick={() => onSave(d)}><Check className="h-3.5 w-3.5" />Salvar</Btn><Btn ghost onClick={onClose}>Cancelar</Btn></div>
      </div>
    </div>
  )
}

export default function Admin() {
  const cms = useCMS(); const { go } = useRouter()
  const [sec, setSec] = useState<string>('overview'); const [side, setSide] = useState(false)
  const [edit, setEdit] = useState<Product | null>(null); const [q, setQ] = useState(''); const [grp, setGrp] = useState('all')
  const { products, setProducts, reviews, setReviews, posts, setPosts, nav, setNav, settings, setSettings, sections, setSections, dict, setDict, fragrances, setFragrances, categories, setCategories, assets, setAssets, leads, setLeads } = cms
  const move = <T,>(arr: T[], i: number, d: number) => { const a = [...arr]; const j = i + d; if (j < 0 || j >= a.length) return a; [a[i], a[j]] = [a[j], a[i]]; return a }

  const views: Record<string, ReactNode> = {
    overview: <>
      <H title="Bom dia." sub="Visão geral da loja São Paulo Aroma" />
      <div className="grid gap-px bg-beige sm:grid-cols-2 xl:grid-cols-4">{[['Leads WhatsApp', String(leads.length), `${leads.filter((l) => l.status === 'Novo').length} novos`], ['Ticket médio', brl(leads.length ? leads.reduce((n, l) => n + l.total, 0) / leads.length : 0), 'pedidos capturados'], ['Produtos publicados', String(products.filter((p) => p.published).length), `${products.filter((p) => p.stock).length} em estoque`], ['Avaliação média', (reviews.filter((r) => r.approved).reduce((n, r) => n + r.rating, 0) / (reviews.filter((r) => r.approved).length || 1)).toFixed(1).replace('.', ','), `${reviews.filter((r) => r.approved).length} reviews`]].map(([l, v, d]) => <div key={l} className="bg-cream p-6"><p className="eyebrow !text-[9px] text-taupe">{l}</p><p className="mt-4 font-serif text-5xl font-light">{v}</p><p className="mt-2 text-xs text-gold">{d}</p></div>)}</div>
      <div className="mt-8 grid gap-8 xl:grid-cols-3">
        <Card className="p-6 xl:col-span-2"><p className="eyebrow mb-6 !text-[9px] text-taupe">Leads por semana</p><div className="flex h-48 items-end gap-3">{[12, 18, 15, 24, 21, 30, 27, 34].map((v, i) => <div key={i} className="flex flex-1 flex-col items-center gap-2"><span className="text-[10px] text-taupe">{v}</span><div className="w-full bg-gold/80" style={{ height: `${v * 4.5}px` }} /><span className="text-[10px] text-taupe">S{i + 1}</span></div>)}</div></Card>
        <Card className="p-6"><p className="eyebrow mb-4 !text-[9px] text-taupe">Mais pedidos</p>{products.slice(0, 5).map((p, i) => <div key={p.id} className="flex items-center gap-3 border-b border-beige/70 py-3 last:border-0"><span className="w-4 text-xs text-taupe">{i + 1}</span><img src={p.imgs[0]} className="h-10 w-10 object-cover" /><span className="flex-1 text-sm">{p.name.pt}</span></div>)}</Card>
      </div>
    </>,
    products: <>
      <H title="Products" sub={`${products.length} produtos`} action={<Btn onClick={() => setEdit({ ...products[0], id: 'novo-produto', sku: 'GA-NEW', name: { pt: '', en: '' }, desc: { pt: '', en: '' }, published: false, featured: false })}><Plus className="h-3.5 w-3.5" />Novo produto</Btn>} />
      <Card className="overflow-x-auto"><table className="w-full min-w-[820px]"><thead><tr><Th>Ordem</Th><Th>Produto</Th><Th>Categoria</Th><Th>Fragrância</Th><Th>Preço</Th><Th>Estoque</Th><Th>Publicado</Th><Th> </Th></tr></thead><tbody>
        {products.map((p, i) => <tr key={p.id} className="hover:bg-ivory"><Td><span className="flex gap-1"><button aria-label="up" onClick={() => setProducts(move(products, i, -1))}><ArrowUp strokeWidth={1} className="h-4 w-4" /></button><button aria-label="down" onClick={() => setProducts(move(products, i, 1))}><ArrowDown strokeWidth={1} className="h-4 w-4" /></button></span></Td>
          <Td><span className="flex items-center gap-3"><img src={p.imgs[0]} className="h-12 w-10 object-cover" /><span><span className="block">{p.name.pt}</span><span className="text-xs text-taupe">{p.name.en} · {p.sku}</span></span></span></Td>
          <Td>{categories.find((c) => c.id === p.cat)?.name.pt || p.cat}</Td><Td>{fragrances.find((f) => f.id === p.frag)?.name.pt || p.frag}</Td><Td className="tabular-nums">{brl(p.price)}</Td>
          <Td><Toggle on={p.stock} onClick={() => setProducts(products.map((x) => x.id === p.id ? { ...x, stock: !x.stock } : x))} /></Td><Td><Toggle on={p.published} onClick={() => setProducts(products.map((x) => x.id === p.id ? { ...x, published: !x.published } : x))} /></Td>
          <Td><span className="flex gap-3"><button onClick={() => setEdit(p)} className="eyebrow !text-[9px] text-gold">Editar</button><button aria-label="delete" onClick={() => setProducts(products.filter((x) => x.id !== p.id))}><Trash2 strokeWidth={1} className="h-4 w-4 text-taupe hover:text-red-800" /></button></span></Td></tr>)}
      </tbody></table></Card>
    </>,
    categories: <><H title="Categories" sub="Nomes refletidos nos filtros e produtos" /><div className="grid gap-px bg-beige sm:grid-cols-2 lg:grid-cols-4">{categories.map((c) => <div key={c.id} className="space-y-4 bg-cream p-6"><In label="Nome — PT" value={c.name.pt} onChange={(v) => setCategories(categories.map((x) => x.id === c.id ? { ...x, name: { ...x.name, pt: v } } : x))} /><In label="Name — EN" value={c.name.en} onChange={(v) => setCategories(categories.map((x) => x.id === c.id ? { ...x, name: { ...x.name, en: v } } : x))} /><p className="eyebrow !text-[9px] text-gold">{products.filter((p) => p.cat === c.id).length} produtos · /{c.id}</p></div>)}</div></>,
    fragrances: <><H title="Fragrances" sub="Textos, cores e imagem das famílias olfativas" /><div className="grid gap-6 lg:grid-cols-2">{fragrances.map((f) => { const upd = (patch: Partial<typeof f>) => setFragrances(fragrances.map((x) => x.id === f.id ? { ...x, ...patch } : x)); return <Card key={f.id} className="p-5"><div className="mb-5 flex gap-5"><img src={f.img} alt="" className="h-28 w-24 object-cover" /><div className="grid flex-1 gap-3 sm:grid-cols-2"><In label="Nome — PT" value={f.name.pt} onChange={(v) => upd({ name: { ...f.name, pt: v } })} /><In label="Name — EN" value={f.name.en} onChange={(v) => upd({ name: { ...f.name, en: v } })} /></div></div><div className="grid gap-4 sm:grid-cols-2"><In label="Notas — PT" value={f.notes.pt} onChange={(v) => upd({ notes: { ...f.notes, pt: v } })} /><In label="Notes — EN" value={f.notes.en} onChange={(v) => upd({ notes: { ...f.notes, en: v } })} /><In area label="Descrição — PT" value={f.desc.pt} onChange={(v) => upd({ desc: { ...f.desc, pt: v } })} /><In area label="Description — EN" value={f.desc.en} onChange={(v) => upd({ desc: { ...f.desc, en: v } })} /><In label="Image URL" value={f.img} onChange={(v) => upd({ img: v })} /><div className="grid grid-cols-3 gap-2"><In label="Fundo" value={f.bg} onChange={(v) => upd({ bg: v })} /><In label="Acento" value={f.accent} onChange={(v) => upd({ accent: v })} /><In label="Texto" value={f.ink} onChange={(v) => upd({ ink: v })} /></div></div></Card> })}</div></>,
    leads: <><H title="Orders / WhatsApp Leads" sub="Pedidos capturados antes de abrir o WhatsApp" /><Card className="overflow-x-auto"><table className="w-full min-w-[850px]"><thead><tr><Th>Pedido</Th><Th>Cliente</Th><Th>Contato</Th><Th>Entrega</Th><Th>Itens</Th><Th>Total</Th><Th>Data</Th><Th>Status</Th></tr></thead><tbody>{leads.length ? leads.map((l) => <tr key={l.id}><Td>{l.id}</Td><Td>{l.customer.name}</Td><Td><span className="block">{l.customer.phone}</span><span className="text-xs text-taupe">{l.customer.email}</span></Td><Td>{l.customer.city} / {l.customer.state}<span className="block text-xs text-taupe">{l.customer.street}, {l.customer.number} · {l.customer.cep}</span></Td><Td>{l.items.reduce((n, i) => n + i.qty, 0)}</Td><Td className="tabular-nums">{brl(l.total)}</Td><Td>{new Date(l.date).toLocaleDateString('pt-BR')}</Td><Td><select aria-label="Status" value={l.status} onChange={(e) => setLeads(leads.map((x) => x.id === l.id ? { ...x, status: e.target.value as OrderLead['status'] } : x))} className="border border-beige bg-ivory px-2 py-1 text-xs">{['Novo', 'Confirmado', 'Enviado', 'Entregue'].map((s) => <option key={s}>{s}</option>)}</select></Td></tr>) : <tr><Td className="py-10 text-center text-taupe" colSpan={8}>Nenhum pedido capturado ainda.</Td></tr>}</tbody></table></Card></>,
    customers: <><H title="Customers" sub="Clientes capturados voluntariamente no checkout" /><Card className="overflow-x-auto"><table className="w-full min-w-[700px]"><thead><tr><Th>Nome</Th><Th>Contato</Th><Th>Cidade</Th><Th>Pedidos</Th><Th>Total</Th></tr></thead><tbody>{Array.from(new Map(leads.map((l) => [l.customer.phone, l.customer])).values()).map((customer) => { const orders = leads.filter((l) => l.customer.phone === customer.phone); return <tr key={customer.phone}><Td>{customer.name}</Td><Td>{customer.phone}<span className="block text-xs text-taupe">{customer.email}</span></Td><Td>{customer.city} / {customer.state}</Td><Td>{orders.length}</Td><Td>{brl(orders.reduce((n, o) => n + o.total, 0))}</Td></tr> })}</tbody></table></Card></>,
    reviews: <><H title="Reviews" action={<Btn><Plus className="h-3.5 w-3.5" />Nova avaliação</Btn>} /><div className="space-y-3">{reviews.map((r) => <Card key={r.id} className="flex flex-wrap items-center gap-6 p-5">{r.photo ? <img src={r.photo} className="h-14 w-14 object-cover" /> : <div className="h-14 w-14 bg-mist" />}<div className="min-w-[240px] flex-1"><div className="flex items-center gap-3"><span className="text-sm font-medium">{r.name}</span><Stars n={r.rating} /><span className="text-xs text-taupe">{r.date}</span></div><p className="mt-1 text-sm text-taupe">{r.text.pt}</p></div>
      <span className="flex items-center gap-2 text-xs">Aprovada<Toggle on={r.approved} onClick={() => setReviews(reviews.map((x) => x.id === r.id ? { ...x, approved: !x.approved } : x))} /></span><span className="flex items-center gap-2 text-xs">Destaque<Toggle on={r.featured} onClick={() => setReviews(reviews.map((x) => x.id === r.id ? { ...x, featured: !x.featured } : x))} /></span><button onClick={() => setReviews(reviews.filter((x) => x.id !== r.id))}><Trash2 strokeWidth={1} className="h-4 w-4 text-taupe hover:text-red-800" /></button></Card>)}</div></>,
    instagram: <><H title="Instagram Content" sub="Posts e Reels exibidos no site" action={<Btn><Plus className="h-3.5 w-3.5" />Adicionar post / reel</Btn>} /><div className="grid grid-cols-2 gap-4 md:grid-cols-4 xl:grid-cols-5">{posts.map((p) => <Card key={p.id}><IgTile post={p} className="aspect-[3/4]" /><div className="flex items-center justify-between p-3"><span className="truncate text-xs">{p.type === 'reel' ? 'Reel' : 'Post'} · {p.title}</span><Toggle on={p.featured} onClick={() => setPosts(posts.map((x) => x.id === p.id ? { ...x, featured: !x.featured } : x))} /></div></Card>)}</div></>,
    pages: <><H title="Pages" /><Card>{[['Sobre', '/sobre'], ['Contato', '/contato'], ['Avaliações', '/avaliacoes'], ['Política de Privacidade', '/privacidade'], ['Termos de Uso', '/termos']].map(([n, u]) => <div key={u} className="flex items-center justify-between border-b border-beige/70 px-5 py-4 last:border-0"><span className="font-serif text-xl">{n}</span><span className="flex items-center gap-4 text-xs text-taupe">{u}<button onClick={() => go(u)}><ExternalLink strokeWidth={1} className="h-4 w-4" /></button></span></div>)}</Card></>,
    translations: (() => {
      const groups = ['all', ...Array.from(new Set(Object.keys(dict).map((k) => k.split('.')[0])))]
      const rows = Object.entries(dict).filter(([k, v]) => (grp === 'all' || k.startsWith(grp + '.')) && (k + v.join(' ')).toLowerCase().includes(q.toLowerCase()))
      const missing = Object.values(dict).filter((v) => !v[1]?.trim()).length
      return <><H title="Translations" sub={`${Object.keys(dict).length} chaves · Português (PT-BR) · English (EN) · ${missing} faltando`} />
        <div className="mb-4 flex flex-wrap items-center gap-3"><div className="flex items-center gap-2 border border-beige bg-cream px-3"><Search strokeWidth={1} className="h-4 w-4 text-taupe" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Buscar chave ou texto" className="bg-transparent py-2.5 text-sm outline-none" /></div><div className="flex flex-wrap gap-1">{groups.map((g) => <button key={g} onClick={() => setGrp(g)} className={`eyebrow px-3 py-2 !text-[9px] ${grp === g ? 'bg-soft text-cream' : 'bg-mist'}`}>{g}</button>)}</div></div>
        <Card className="overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr><Th>Key</Th><Th>Português — PT-BR</Th><Th>English — EN</Th></tr></thead><tbody>{rows.map(([k, [pt, en]]) => <tr key={k}><Td className="w-56 font-mono text-xs text-gold">{k}</Td>{[pt, en].map((v, i) => <Td key={i}><textarea rows={1} value={v} onChange={(e) => { const n = [...dict[k]] as [string, string]; n[i] = e.target.value; setDict({ ...dict, [k]: n }) }} className={`w-full resize-y border bg-transparent px-2 py-1.5 text-sm outline-none focus:border-gold ${v.trim() ? 'border-transparent hover:border-beige' : 'border-red-800/50'}`} /></Td>)}</tr>)}</tbody></table></Card></>
    })(),
    navigation: <><H title="Navigation" sub="Itens do menu principal — refletem imediatamente no site" action={<Btn onClick={() => setNav([...nav, { id: 'n' + Date.now(), label: { pt: 'Novo', en: 'New' }, url: '/', order: nav.length + 1, visible: false, external: false }])}><Plus className="h-3.5 w-3.5" />Novo item</Btn>} />
      <Card className="overflow-x-auto"><table className="w-full min-w-[760px]"><thead><tr><Th>Ordem</Th><Th>Label PT</Th><Th>Label EN</Th><Th>URL</Th><Th>Visível</Th><Th>Externo</Th><Th> </Th></tr></thead><tbody>{[...nav].sort((a, b) => a.order - b.order).map((n, i, arr) => {
        const upd = (patch: Partial<typeof n>) => setNav(nav.map((x) => x.id === n.id ? { ...x, ...patch } : x))
        const swap = (d: number) => { const o = arr[i + d]; if (!o) return; setNav(nav.map((x) => x.id === n.id ? { ...x, order: o.order } : x.id === o.id ? { ...x, order: n.order } : x)) }
        return <tr key={n.id}><Td><span className="flex gap-1"><button onClick={() => swap(-1)}><ArrowUp strokeWidth={1} className="h-4 w-4" /></button><button onClick={() => swap(1)}><ArrowDown strokeWidth={1} className="h-4 w-4" /></button></span></Td>
          <Td><input value={n.label.pt} onChange={(e) => upd({ label: { ...n.label, pt: e.target.value } })} className="w-full border border-transparent bg-transparent px-2 py-1 hover:border-beige focus:border-gold focus:outline-none" /></Td><Td><input value={n.label.en} onChange={(e) => upd({ label: { ...n.label, en: e.target.value } })} className="w-full border border-transparent bg-transparent px-2 py-1 hover:border-beige focus:border-gold focus:outline-none" /></Td>
          <Td><input value={n.url} onChange={(e) => upd({ url: e.target.value })} className="w-full border border-transparent bg-transparent px-2 py-1 font-mono text-xs hover:border-beige focus:border-gold focus:outline-none" /></Td><Td><Toggle on={n.visible} onClick={() => upd({ visible: !n.visible })} /></Td><Td><Toggle on={n.external} onClick={() => upd({ external: !n.external })} /></Td><Td><button onClick={() => setNav(nav.filter((x) => x.id !== n.id))}><Trash2 strokeWidth={1} className="h-4 w-4 text-taupe" /></button></Td></tr>
      })}</tbody></table></Card></>,
    homepage: <><H title="Homepage Builder" sub="Ative, desative e reordene as seções da página inicial" /><div className="space-y-2">{sections.map((s, i) => <Card key={s.id} className={`flex items-center gap-5 px-5 py-4 transition-opacity ${s.on ? '' : 'opacity-50'}`}><span className="font-serif text-2xl italic text-gold/70">{String(i + 1).padStart(2, '0')}</span><span className="flex-1 font-serif text-2xl">{s.label}</span><span className="hidden text-xs text-taupe md:block">Título · Subtítulo · Imagem · CTA</span><button onClick={() => setSections(move(sections, i, -1))}><ArrowUp strokeWidth={1} className="h-4 w-4" /></button><button onClick={() => setSections(move(sections, i, 1))}><ArrowDown strokeWidth={1} className="h-4 w-4" /></button><button onClick={() => setSections(sections.map((x) => x.id === s.id ? { ...x, on: !x.on } : x))}>{s.on ? <Eye strokeWidth={1} className="h-4 w-4" /> : <EyeOff strokeWidth={1} className="h-4 w-4" />}</button></Card>)}</div>
      <Card className="mt-8 grid gap-5 p-6 md:grid-cols-2"><p className="eyebrow !text-[9px] text-gold md:col-span-2">Hero</p>{(['hero.title1', 'hero.title2', 'hero.sub', 'hero.cta'] as const).map((k) => [0, 1].map((i) => <In key={k + i} label={`${k} — ${i ? 'EN' : 'PT'}`} value={dict[k][i]} onChange={(v) => { const n = [...dict[k]] as [string, string]; n[i] = v; setDict({ ...dict, [k]: n }) }} />))}</Card></>,
    contact: <><H title="Contact Information" sub="Exibido no rodapé, contato, mapa e mensagens de WhatsApp" /><Card className="grid gap-5 p-6 md:grid-cols-2">{(['whatsapp', 'phone', 'email', 'address', 'instagram', 'facebook'] as const).map((k) => <In key={k} label={k} value={settings[k]} onChange={(v) => setSettings({ ...settings, [k]: v })} />)}<div className="md:col-span-2"><In label="OpenStreetMap embed URL" value={settings.mapUrl} onChange={(v) => setSettings({ ...settings, mapUrl: v })} /></div><In label="Business hours — PT" value={settings.hours.pt} onChange={(v) => setSettings({ ...settings, hours: { ...settings.hours, pt: v } })} /><In label="Business hours — EN" value={settings.hours.en} onChange={(v) => setSettings({ ...settings, hours: { ...settings.hours, en: v } })} /></Card></>,
    seo: <><H title="SEO" sub="Limites recomendados: título 60 · descrição 160" />
      <Card className="mb-8 grid gap-5 p-6 md:grid-cols-2"><p className="eyebrow !text-[9px] text-gold md:col-span-2">Global</p><In label="Site title" max={60} value={dict['seo.home'][0]} onChange={(v) => setDict({ ...dict, 'seo.home': [v, dict['seo.home'][1]] })} /><In label="Canonical URL" value="https://saopauloaroma.com.br" onChange={() => {}} /><In area label="Meta description" max={160} value={dict['hero.sub'][0] + ' Velas, difusores, home sprays e sabonetes.'} onChange={() => {}} /><In label="Keywords" value="velas aromáticas, difusor de varetas, home spray, São Paulo" onChange={() => {}} /></Card>
      <div className="mb-8 border border-beige bg-cream p-6"><p className="eyebrow mb-3 !text-[9px] text-taupe">Pré-visualização Google</p><p className="text-sm text-[#1a0dab]">{dict['seo.home'][0]}</p><p className="text-xs text-[#006621]">saopauloaroma.com.br</p><p className="mt-1 max-w-xl text-xs text-soft/70">{dict['hero.sub'][0]}</p></div>
      <Card className="overflow-x-auto"><table className="w-full min-w-[700px]"><thead><tr><Th>Página</Th><Th>Slug</Th><Th>SEO title</Th><Th>Meta description</Th></tr></thead><tbody>{[['Home', '/', dict['seo.home'][0], dict['hero.sub'][0]], ['Produtos', '/produtos', 'Nossos Produtos | São Paulo Aroma', dict['prod.sub'][0]], ['Sobre', '/sobre', 'Sobre a São Paulo Aroma', dict['about.sub'][0]], ['Avaliações', '/avaliacoes', 'Avaliações | São Paulo Aroma', 'Experiências que ficam na memória.'], ['Contato', '/contato', 'Contato | São Paulo Aroma', dict['contact.sub'][0]]].map(([n, s, ti, d]) => <tr key={s}><Td>{n}</Td><Td className="font-mono text-xs">{s}</Td><Td><span className={ti.length > 60 ? 'text-red-800' : ''}>{ti}</span> <span className="text-[10px] text-taupe">{ti.length}/60</span></Td><Td><span className="text-xs">{d}</span> <span className="text-[10px] text-taupe">{d.length}/160</span></Td></tr>)}</tbody></table></Card></>,
    media: <><H title="Media Library" sub="Cole URLs públicas para atualizar imagens em todo o site" /><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">{Object.entries(assets).map(([k, v]) => <Card key={k} className="p-3"><div className="aspect-[16/10] overflow-hidden bg-mist"><img loading="lazy" src={v} alt="" className="h-full w-full object-cover" /></div><label className="mt-3 block"><span className="eyebrow !text-[9px] text-gold">{k}</span><input value={v} onChange={(e) => setAssets({ ...assets, [k]: e.target.value })} className="mt-2 w-full border border-beige bg-ivory px-2 py-2 text-xs outline-none focus:border-gold" /></label></Card>)}</div></>,
    settings: <><H title="Settings" /><Card className="grid gap-5 p-6 md:grid-cols-2"><div className="flex items-center gap-6 md:col-span-2"><img src={assets.logo} className="h-20 w-20 border border-beige object-cover" /><In label="Logo URL" value={assets.logo} onChange={(v) => setAssets({ ...assets, logo: v })} /></div><In label="Brand name" value={settings.brand} onChange={(v) => setSettings({ ...settings, brand: v })} /><In label="Currency" value={settings.currency} onChange={(v) => setSettings({ ...settings, currency: v })} />
      <div><p className="eyebrow mb-2 !text-[9px] text-taupe">Default language</p><div className="flex gap-2">{(['pt', 'en'] as const).map((l) => <button key={l} onClick={() => setSettings({ ...settings, defaultLang: l })} className={`eyebrow px-4 py-2 !text-[10px] ${settings.defaultLang === l ? 'bg-soft text-cream' : 'border border-beige'}`}>{l === 'pt' ? 'Português — PT-BR' : 'English — EN'}</button>)}</div></div>
      <In area label="Footer text — PT" value={dict['footer.statement'][0]} onChange={(v) => setDict({ ...dict, 'footer.statement': [v, dict['footer.statement'][1]] })} /></Card></>,
  }

  return (
    <div className="flex min-h-screen bg-ivory text-soft">
      <aside className={`fixed inset-y-0 left-0 z-40 w-64 overflow-y-auto border-r border-beige bg-cream transition-transform duration-700 ease-lux lg:translate-x-0 ${side ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="flex items-center justify-between border-b border-beige px-6 py-6"><Logo /><span className="eyebrow !text-[8px] text-gold">CMS</span></div>
        <nav className="p-3">{SECTIONS_ADMIN.map(([id, label, I]) => <button key={id} onClick={() => { setSec(id); setSide(false) }} className={`flex w-full items-center gap-3 px-3 py-2.5 text-left text-[13px] transition ${sec === id ? 'bg-soft text-cream' : 'text-soft/80 hover:bg-mist'}`}><I strokeWidth={1} className="h-4 w-4" />{label}</button>)}</nav>
      </aside>
      <div className="flex-1 lg:pl-64">
        <header className="sticky top-0 z-30 flex items-center justify-between border-b border-beige bg-ivory/90 px-5 py-4 backdrop-blur md:px-10">
          <button className="lg:hidden" onClick={() => setSide(!side)} aria-label="Menu"><Menu strokeWidth={1} /></button>
          <p className="eyebrow hidden !text-[9px] text-taupe lg:block">São Paulo Aroma · Admin / {SECTIONS_ADMIN.find((s) => s[0] === sec)?.[1]}</p>
          <div className="flex items-center gap-4"><button onClick={() => go('/')} className="eyebrow flex items-center gap-2 !text-[9px] hover:text-gold"><ExternalLink strokeWidth={1} className="h-3.5 w-3.5" />Ver site</button><span className="flex h-8 w-8 items-center justify-center rounded-full bg-gold font-serif text-cream">G</span></div>
        </header>
        <main key={sec} className="animate-[adminIn_.8s_cubic-bezier(.22,1,.36,1)] px-5 py-10 md:px-10">{views[sec]}</main>
      </div>
      {edit && <ProductEditor p={edit} onClose={() => setEdit(null)} onSave={(p) => { setProducts(products.some((x) => x.id === edit.id) ? products.map((x) => x.id === edit.id ? p : x) : [...products, p]); setEdit(null) }} />}
    </div>
  )
}
